### ISSUE TITLE
임시 비밀번호 요청시 없는 이메일이면 500 서버 에러 응답이 돌아옴

### ISSUE THREAD

**Issue by henry174** [yachugak/TOPLA#130]
따라서 프론트엔드에서 화면에 표시해 줄 내용이 없음. 제대로 된 에러를 던지도록 수정해야 함.

**Comment by romaakk** [comment]
issue/130 진행중

**Comment by henry174** [comment]
이거 아직 병합 안 됐나?

**Comment by romaakk** [comment]
> 이거 아직 병합 안 됐나?

병합되었음. Pull Request 링크를 안걸어뒀음.
