### ISSUE TITLE
임시비밀번호, 이메일 인증에 이용하는 randomCode 반환 타입 변경

### ISSUE THREAD

**Issue by romaakk** [yachugak/TOPLA#138]
기존
* DB INT
* Int

=> TEXT, String으로 변경 필요

**Comment by henry174** [comment]
숫자만 있었는데 이제 문자로 바꾸게?

**Comment by fnai** [comment]
> 숫자만 있었는데 이제 문자로 바꾸게?

ㅇㅇ 만약에 앞에 0이면 패딩해줘야하는데 제대로 안들어갈수도 있어서

**Comment by fnai** [comment]
138로 12/9에 바로 수정해서 풀리퀘스트 때렸슴니다.
