### ISSUE TITLE
다른 기기에서 로그인했다가 원래 기기로 돌아올 시 인증이 안 되는 버그

### ISSUE THREAD

**Issue by henry174** [yachugak/TOPLA#171]
이 버그가 일어나는 과정은
A 기기에서 로그인 하면 랜덤 토큰 a를 받음.
이후 B 기기에서 로그인하면 랜덤 토큰 b를 새로 발급 받음
다시 원래 기기 A로 돌아오면 로그인 정보가 남아있어 로그인 페이지를 스킵하지만 정작 A기기에 저장되어 있는 랜덤 토큰은 a라 인증이 되지 않아 아무것도 못 함.
사실 로그아웃하고 다시 로그인하면 됨. 따라서 인증 토큰이 다른 경우 로그인 페이지로 돌려 버리는 기능이 필요함.

**Comment by fnai** [comment]
가져감니다

**Comment by henry174** [comment]
위 작업 무시할 것
issue/171-2에서 작업중.

**Comment by fnai** [comment]
흨흨 뺏김
