### ISSUE TITLE
에러 메세지에서 에러코드 빼기

### ISSUE THREAD

**Issue by henry174** [yachugak/TOPLA#178]
지금 서버 처리하다가 예외 던저지면 프론트엔드에서

[errorCode] 에러메세지

이렇게 뜨는데 생각해 보니 에러 코드는 보여줄 필요가 없는듯

**Comment by romaakk** [comment]
원래 개발용으로 썼었는데 그냥 프론트로 돌려서 고래된덧 
ㅇㅈ합니다
