### ISSUE TITLE
슈퍼유저 비번 리셋 프론트에서 준 값으로 하기?

### ISSUE THREAD

**Issue by romaakk** [yachugak/TOPLA#181]

**Comment by henry174** [comment]
기본 비밀번호 0000보다는 낫지 않냐?

선우가 걱정하는게 실수로 잘못된 이메일을 적어서 이메일을 받을 수 없게된 사람들의 경우 비밀번호를 못 찾는다는 건데 최고의 해결 방법은

1. 슈퍼 유저의 회원들의 계정(이메일) 변경 가능
1. 슈퍼 유저가 본인 인증이 된 회원의 계정을 정상 이메일로 변경
1. 그 후 슈퍼 유저가 비밀번호 초기화(0000이 아니라 랜덤)시킴
1. 유저는 자신의 정상 이메일로 초기화된 비밀번호를 받아 로그인 가능.

**Comment by fnai** [comment]
승준이 말이 맞는거 같음 그리고 정상이메일이 아닌데 회원가입을 할수 없다는것도 알아둬야함
현재 이메일 인증을 해야하는데 그거 인증 못하면 회원가입도 못함

**Comment by romaakk** [comment]
> 기본 비밀번호 0000보다는 낫지 않냐?
> 
> 선우가 걱정하는게 실수로 잘못된 이메일을 적어서 이메일을 받을 수 없게된 사람들의 경우 비밀번호를 못 찾는다는 건데 최고의 해결 방법은
> 
> 1. 슈퍼 유저의 회원들의 계정(이메일) 변경 가능
> 2. 슈퍼 유저가 본인 인증이 된 회원의 계정을 정상 이메일로 변경
> 3. 그 후 슈퍼 유저가 비밀번호 초기화(0000이 아니라 랜덤)시킴
> 4. 유저는 자신의 정상 이메일로 초기화된 비밀번호를 받아 로그인 가능.

front에서 준 값으로 변경하는걸로 바꿈 그럼.
내가 걱정되는건, 이걸 시연한다고 했을 때
"관리자는 유저의 비밀번호를 바꿀수도 있습니다.." 이런식으로 설명해야 되니까.

**Comment by fnai** [comment]
> front에서 준 값으로 변경하는걸로 바꿈 그럼.
> 내가 걱정되는건, 이걸 시연한다고 했을 때
> "관리자는 유저의 비밀번호를 바꿀수도 있습니다.." 이런식으로 설명해야 되니까.

"유저의 요청이 있을경우 유저의 정보를 슈퍼유저가 변경할 수 있습니다."라고 말하면 될듯?

**Comment by henry174** [comment]
> > 기본 비밀번호 0000보다는 낫지 않냐?
> > 선우가 걱정하는게 실수로 잘못된 이메일을 적어서 이메일을 받을 수 없게된 사람들의 경우 비밀번호를 못 찾는다는 건데 최고의 해결 방법은
> > 
> > 1. 슈퍼 유저의 회원들의 계정(이메일) 변경 가능
> > 2. 슈퍼 유저가 본인 인증이 된 회원의 계정을 정상 이메일로 변경
> > 3. 그 후 슈퍼 유저가 비밀번호 초기화(0000이 아니라 랜덤)시킴
> > 4. 유저는 자신의 정상 이메일로 초기화된 비밀번호를 받아 로그인 가능.
> 
> front에서 준 값으로 변경하는걸로 바꿈 그럼.
> 내가 걱정되는건, 이걸 시연한다고 했을 때
> "관리자는 유저의 비밀번호를 바꿀수도 있습니다.." 이런식으로 설명해야 되니까.

"관리자가 유저의 비밀 번호를 바꿀 수도 있습니다"는 임시 비밀번호라도 마찬가지잖아

**Comment by henry174** [comment]
issue/181-2에서 프론트엔드 작업 진행중
