### ISSUE TITLE
Topbar에서 일간 보기 <-> 월간 보기 전환 버튼 뺄까?

### ISSUE THREAD

**Issue by henry174** [yachugak/TOPLA#183]
조교님은 빼기를 원하는 것 같음.

**Comment by fnai** [comment]
나는 아이콘만 바꾸면 그자리에 있어도 될거같음
조교님도 다른거 보시고서는 아 그렇네요 그러시고는 아이콘이 이상하다 하셨음

**Comment by henry174** [comment]
괜찮은 아이콘 없나

**Comment by romaakk** [comment]
> 괜찮은 아이콘 없나

아이콘이 좀 직관적이지가 않아서 그런것 같다고 생각합니다. 그 책상을 좀 바꾸면 될듯합니다.
아예 우리 페이지랑 비슷한 아이콘을 찾아왔습니다.


* TODO
![image](https://user-images.githubusercontent.com/54837412/102006510-f9afbd00-3d64-11eb-88e8-cdfa0fab4dd6.png)
=> https://material.io/resources/icons/?search=stack&icon=calendar_today&style=baseline


* 달력
![image](https://user-images.githubusercontent.com/54837412/102006538-4398a300-3d65-11eb-9ede-3df7b5dcc499.png)
=> https://material.io/resources/icons/?search=day&icon=calendar_today&style=baseline

**Comment by romaakk** [comment]
> > 괜찮은 아이콘 없나
> 
> 아이콘이 좀 직관적이지가 않아서 그런것 같다고 생각합니다. 그 책상을 좀 바꾸면 될듯합니다.
> 아예 우리 페이지랑 비슷한 아이콘을 찾아왔습니다.
> 
> * TODO
>   ![image](https://user-images.githubusercontent.com/54837412/102006510-f9afbd00-3d64-11eb-88e8-cdfa0fab4dd6.png)
>   => https://material.io/resources/icons/?search=stack&icon=calendar_today&style=baseline
> * 달력
>   ![image](https://user-images.githubusercontent.com/54837412/102006538-4398a300-3d65-11eb-9ede-3df7b5dcc499.png)
>   => https://material.io/resources/icons/?search=day&icon=calendar_today&style=baseline

햄버거 버튼을 생각못했네요.
TODO 적당한거 없으면 그냥 빼야할듯

**Comment by fnai** [comment]
적당한거 없으면 빼야될듯 ㅇㅇ

**Comment by romaakk** [comment]
> 적당한거 없으면 빼야될듯 ㅇㅇ

아까 올린 fact check는 괜찮아 뵈던데

**Comment by fnai** [comment]
> 아까 올린 fact check는 괜찮아 뵈던데

일단 프론트에서 반영된걸 봐야할듯함

**Comment by henry174** [comment]
아이콘 변경 이슈로 다시 등록함
