### ISSUE TITLE
메인으로 돌아가는 버튼 배치하기

### ISSUE THREAD

**Issue by henry174** [yachugak/TOPLA#184]
조교님은 이게 있는지도 본다고 했음.
지금 화면 디자인에서 가장 좋은 건 Topla 이름을 클릭하면 메인으로 가거나, 사이드바에 메인으로 가는 버튼을 넣는 거임.

**Comment by fnai** [comment]
개인적으로는 topla이름 클릭하면 메인가는게 제일 좋아보임
