### ISSUE TITLE
작업 등록시 마감일 자동으로 채우기?

### ISSUE THREAD

**Issue by romaakk** [yachugak/TOPLA#197]
급한건 아닙니다.

작업 추가한 페이지의 날짜를 기본값으로?

**Comment by fnai** [comment]
그럼 오늘날짜로 추가되는건가여

**Comment by romaakk** [comment]
> 그럼 오늘날짜로 추가되는건가여

직전 페이지 기준으로
+버튼 눌렀을 때의 기준
