### ISSUE TITLE
새로 만든 유저의 아침 알림 시간이 00시임 

### ISSUE THREAD

**Issue by romaakk** [yachugak/TOPLA#203]

**Comment by fnai** [comment]
이거 생각해보니 원인은 우리가 utc+0으로 디비에 때려박았는데 정작 쓰는건 그 시간을 제대로 써서 그럼
일단 내가 그부분 수정은 해서 커밋은 해두는데 이건 얘기 더 해봐야할거같네여

**Comment by fnai** [comment]
계속 찾아봤는데 time은 그냥 ㄹㅇ 시간만 받는거라서 오프셋타임과 호환이 안되는거 같음
그래서 그냥 애초에 시간을 9시간 더해서 넣거나 아니면 디비에서 타입을 바꿔야 할거같음

**Comment by romaakk** [comment]
> 계속 찾아봤는데 time은 그냥 ㄹㅇ 시간만 받는거라서 오프셋타임과 호환이 안되는거 같음
> 그래서 그냥 애초에 시간을 9시간 더해서 넣거나 아니면 디비에서 타입을 바꿔야 할거같음

time으로 바뀜?
저게 원래 안되던게 아니라 어느순간부터 안된거라 그럼

**Comment by fnai** [comment]
> time으로 바뀜?
> 저게 원래 안되던게 아니라 어느순간부터 안된거라 그럼

일단 지금 데이터타입이 time이긴 함
내가 계속 코드 바꿔가면서 확인해봤는데 안먹히는게 맞는거같음

**Comment by fnai** [comment]
좀더 연구를 해봤는데 지역시간대가 입력이 되긴 합니다
그런데 그 정보를 가지고만 있고 utc+0로 디비에 저장이 됨니다
그리고 지금은 우리가 디비에서 시간을 직접 비교하다보니까 그부분에서 문제가 생긴거 같습니다

**Comment by fnai** [comment]
해결 완료
