### ISSUE TITLE
작업보기에서 구분선 있는게 좋지 않을까

### ISSUE THREAD

**Issue by fnai** [yachugak/TOPLA#207]
작업보기에서 작업이 없는날은 뭔가 아래로 너무 휑한데 구분선 하나 넣는거 어떤가여
![image](https://user-images.githubusercontent.com/64246362/102045464-7d78b080-3e1c-11eb-9391-09cc4fd7a13d.png)

**Comment by fnai** [comment]
이런식으로

**Comment by henry174** [comment]
뭐야 사진 어케 넣음

**Comment by fnai** [comment]
> 뭐야 사진 어케 넣음

그냥 사진 복붙하면 사진 주소가 내용에 들어감
그렇게되면 사진이 잘 뜸니다
